using Triangulate
using Grid
using Quadrature
using ExtendableSparse
using LinearAlgebra
using SparseArrays
using FiniteElements
using FESolveCommon
using FESolveStokes
using FESolvePoisson
using ForwardDiff
ENV["MPLBACKEND"]="tkagg"
using PyPlot


function triangulate_unitsquare(maxarea)
    triin=Triangulate.TriangulateIO()
    triin.pointlist=Matrix{Cdouble}([0 0; 1 0; 1 1; 0 1]');
    triin.segmentlist=Matrix{Cint}([1 2 ; 2 3 ; 3 4 ; 4 1 ]')
    triin.segmentmarkerlist=Vector{Int32}([1, 2, 3, 4])
    (triout, vorout)=triangulate("pQa" * string(maxarea), triin)
    return Grid.Mesh{Float64}(Array{Float64,2}(triout.pointlist'),Array{Int64,2}(triout.trianglelist'),Grid.ElemType2DTriangle());
end


function main()

fem = "BR"

use_problem = "P7vortex"; u_order = 7; error_order = 6; p_order = 3; f_order = 5;
#use_problem = "constant"; u_order = 0; error_order = 0; p_order = 0; f_order = 0;
#use_problem = "linear"; u_order = 1; error_order = 2; p_order = 0; f_order = 0;
#use_problem = "quadratic"; u_order = 2; error_order = 2; p_order = 1; f_order = 0;
#use_problem = "cubic"; u_order = 3; error_order = 4; p_order = 2; f_order = 1;
maxlevel = 4
nu = [1,1e-2,1e-4]

show_convergence_history = true


# define problem data
function theta(problem) # stream function
    function closure(x)
        if problem == "linear"
            return - x[2]^2 * 1//2;
        elseif problem == "P7vortex"
            return x[1]^2 * (x[1] - 1)^2 * x[2]^2 * (x[2] - 1)^2
        elseif problem == "quadratic"
            return x[1]^3+x[2]^3;
        elseif problem == "cubic"
            return x[1]^4+x[2]^4;  
        elseif problem == "constant"
            return x[1] + x[2];    
        end
    end    
end    


function exact_pressure(problem) # exact pressure
    function closure(x)
        if problem == "P7vortex"
            return x[1]^3 + x[2]^3 - 1//2 
        elseif problem == "quadratic"
            return x[1] - 1//2;    
        elseif problem == "cubic"
            return x[1]^2 + x[2]^2 - 2//3;    
        else
            return 0;    
        end
    end    
end


function volume_data!(problem, nu, poisson = false) # volume data (generated by FowardDiff)
    hessian = [0.0 0.0;0.0 0.0]
    p(x) = exact_pressure(problem)(x)
    u(x) = exact_solution(problem)(x)
    pgrad = DiffResults.GradientResult([0.0,0.0]);
    hessian = DiffResults.HessianResult([0.0,0.0]);
    velo_rotated(a) = ForwardDiff.gradient(theta(problem),a);
    velo1 = x -> -velo_rotated(x)[2]
    velo2 = x -> velo_rotated(x)[1]
    return function closure(result, x)  
        # compute gradient of pressure
        ForwardDiff.gradient!(pgrad,p,x);
        if (poisson)
            result[1] = 0
            result[2] = 0
        else
            result[1] = DiffResults.gradient(pgrad)[1]
            result[2] = DiffResults.gradient(pgrad)[2]
        end    
        # add Laplacian of velocity
        ForwardDiff.hessian!(hessian,velo1,x)
        result[1] -= nu * (DiffResults.hessian(hessian)[1] + DiffResults.hessian(hessian)[4])
        ForwardDiff.hessian!(hessian,velo2,x)
        result[2] -= nu * (DiffResults.hessian(hessian)[1] + DiffResults.hessian(hessian)[4])
    end    
end


function exact_velocity!(problem) # velocity (= curl(theta), generated by FowardDiff)
    thetagrad = DiffResults.GradientResult([0.0,0.0]);
    return function closure(result, x)
        ForwardDiff.gradient!(thetagrad,theta(problem),x);
        result[1] = -DiffResults.gradient(thetagrad)[2]
        result[2] = DiffResults.gradient(thetagrad)[1]
    end    
    
end

function wrap_pressure(result,x)
    result[1] = exact_pressure(use_problem)(x)
end    

L2error_velocity = zeros(Float64,length(nu),maxlevel)
L2error_pressure = zeros(Float64,length(nu),maxlevel)
L2error_velocity_reconst = zeros(Float64,length(nu),maxlevel)
L2error_pressure_reconst = zeros(Float64,length(nu),maxlevel)

ndofs = zeros(Int,maxlevel)

for level = 1 : maxlevel

println("Solving Stokes problem on refinement level...", level);
println("Generating grid by triangle...");
maxarea = 4.0^(-level)
grid = triangulate_unitsquare(maxarea)
Grid.show(grid)

# load finite element
if fem == "BR"
    # Bernardi--Raugel with RT0 reconstruction
    FE_velocity = FiniteElements.getBRFiniteElement(grid,2);
    FE_pressure = FiniteElements.getP0FiniteElement(grid,1);
end    
FiniteElements.show(FE_velocity)
FiniteElements.show(FE_pressure)
ndofs_velocity = FiniteElements.get_ndofs(FE_velocity);
ndofs_pressure = FiniteElements.get_ndofs(FE_pressure);
ndofs[level] = ndofs_velocity + ndofs_pressure;

for nu_index = 1 : length(nu)
    # solve Stokes problem
    val4dofs = zeros(Base.eltype(grid.coords4nodes),ndofs[level]);
    residual = solveStokesProblem!(val4dofs,nu[nu_index],volume_data!(use_problem,nu[nu_index]),exact_velocity!(use_problem),grid,FE_velocity,FE_pressure,FiniteElements.get_polynomial_order(FE_velocity)+f_order, false);
    val4dofs_reconst = zeros(Base.eltype(grid.coords4nodes),ndofs[level]);
    residual = solveStokesProblem!(val4dofs_reconst,nu[nu_index],volume_data!(use_problem,nu[nu_index]),exact_velocity!(use_problem),grid,FE_velocity,FE_pressure,FiniteElements.get_polynomial_order(FE_velocity)+f_order, true);
    
    # compute errors
    integral4cells = zeros(size(grid.nodes4cells,1),1);
    integrate!(integral4cells,eval_L2_interpolation_error!(wrap_pressure, val4dofs[ndofs_velocity+1:end], FE_pressure), grid, error_order, 1);
    L2error_pressure[nu_index,level] = sqrt(abs(sum(integral4cells)));
    integrate!(integral4cells,eval_L2_interpolation_error!(wrap_pressure, val4dofs_reconst[ndofs_velocity+1:end], FE_pressure), grid, error_order, 1);
    L2error_pressure_reconst[nu_index,level] = sqrt(abs(sum(integral4cells)));
   

    integral4cells = zeros(size(grid.nodes4cells,1),2);
    integrate!(integral4cells,eval_L2_interpolation_error!(exact_velocity!(use_problem), val4dofs[1:ndofs_velocity], FE_velocity), grid, error_order, 2);
    L2error_velocity[nu_index,level] = sqrt(abs(sum(integral4cells[:])));
    integrate!(integral4cells,eval_L2_interpolation_error!(exact_velocity!(use_problem), val4dofs_reconst[1:ndofs_velocity], FE_velocity), grid, error_order, 2);
    L2error_velocity_reconst[nu_index,level] = sqrt(abs(sum(integral4cells[:])));
 
end # loop over nu
end # loop over levels

println("\n L2 pressure error");
show(L2error_pressure)
println("\n L2 velocity error");
show(L2error_velocity)

if (show_convergence_history)
    for nu_index = 1 : length(nu)
        PyPlot.figure(nu_index)
        PyPlot.loglog(ndofs,L2error_velocity[nu_index,:],"-o")
        PyPlot.loglog(ndofs,L2error_velocity_reconst[nu_index,:],"-o")
        PyPlot.loglog(ndofs,ndofs.^(-1/2),"--",color = "gray")
        PyPlot.loglog(ndofs,ndofs.^(-1),"--",color = "gray")
        PyPlot.loglog(ndofs,ndofs.^(-3/2),"--",color = "gray")
        PyPlot.legend(("L2 error velocity " * fem,"L2 error velocity " * fem * "+","L2 error pressure " * fem,"L2 error pressure " * fem * "+","O(h)","O(h^2)","O(h^3)"))
        PyPlot.title("Convergence history (fem=" * fem * " nu=" * string(nu[nu_index]) * " problem=" * use_problem * ")")
        ax = PyPlot.gca()
        ax.grid(true)
    end    
end    

    
end


main()
